# Dependencies
markdown:  redcarpet
highlighter:  rogue

# Permalinks
permalink:  writing/:title

# Setup
title:  MadebyMike
url:  http://madebymike.com.au
paginate:  5
paginate_path:  "writing/:num"
baseurl:  /
exclude:  [node_modules, package.json, npm-debug.log, Gruntfile.js, scss]
author:
  name:  Mike Riethmuller
  url:  http://madebymike.com.au
  email:  mike@madebymike.com.au

# Custom vars
version:  1.0.0
github:  https://github.com/MadeByMike/madebymike.github.io
repo:  https://github.com/MadeByMike/madebymike.github.io