backend:
  name: git-gateway
  branch: "redesign"
  repo: "MadeByMike/madebymike.github.io"

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "articles" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Article" # Used in the UI, ie.: "New Post"
    folder: "site/content/writing" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
    - {label: Title, name: title, widget: string}
    - {label: Date, name: date, widget: datetime}
    - {label: Description, name: description, widget: markdown}
    - {label: 'Extra CSS', name: extra_css, widget: list, required: false}
    - {label: 'Extra JS', name: extra_js, widget: list, required: false}
    - {label: 'Card size', name: card_size, widget: select, options: [{label: Tall, value: tall}, {label: Wide, value: wide}, {label: Large, value: large}, {label: Huge, value: huge}], required: false}
    - {label: Image, name: image, widget: image, required: false}
    - {label: "No link", name: "no_link", widget: "boolean", default: false, required: false}
    - {label: "External Link", name: "external_link", widget: "string", required: false}
    - {label: Body, name: body, widget: markdown, required: false}

  - name: "lists" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "List" # Used in the UI, ie.: "New Post"
    folder: "site/content/lists" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Extra CSS", name: "extra_css", widget: "list", required: false}
      - {label: "Extra JS", name: "extra_js", widget: "list", required: false}
      - {label: "Card size", name: "card_size", widget: "select", options: [{label: "Tall", value: "tall"}, {label: "Wide", value: "wide"}, {label: "Large", value: "large"}, {label: "Huge", value: "huge"}], required: false }
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "No link", name: "no_link", widget: "boolean", default: true, required: false}
      - {label: "External Link", name: "external_link", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      
  - name: "pens" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pen" # Used in the UI, ie.: "New Post"
    folder: "site/content/pens" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Extra CSS", name: "extra_css", widget: "list", required: false}
      - {label: "Extra JS", name: "extra_js", widget: "list", required: false}
      - {label: "Card size", name: "card_size", widget: "select", options: [{label:"Tall", value:"tall"}, {label:"Wide", value: "wide"}, {label:"Large", value: "large"}, {label:"Huge", value: "huge"}], required: false }
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "No link", name: "no_link", widget: "boolean", default: false, required: false}
      - {label: "External Link", name: "external_link", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "not-ads" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Not Ad" # Used in the UI, ie.: "New Post"
    folder: "site/content/pens" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Extra CSS", name: "extra_css", widget: "list", required: false}
      - {label: "Extra JS", name: "extra_js", widget: "list", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "No link", name: "no_link", widget: "boolean", default: false}
      - {label: "External Link", name: "external_link", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
      - file: "site/content/hire/_index.md"
        label: "Hire Me"
        name: "Hire Me"
        fields:
          - {label: Title, name: title, widget: string}